In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Loading DataFrame

In [ ]:
customer_data = pd.read_csv('Training.csv')
testing_data = pd.read_csv('testing.csv')

In [ ]:
customer_data.head()

,customer_unique_id,Recency,Frequency,Total_Spent,Average_Review_Score,Avg_Late_Delivery_Days,Repeat_Purchase
0,0000f46a3911fa3c0805444483337064,296,1,86.22,3,0.0,0
1,0000f6ccb0745a6a4b88665a16c9f078,80,1,43.62,4,0.0,0
2,0004aac84e0df4da2b147fca70cf8255,47,1,196.89,5,0.0,0
3,0005e1862207bf6ccc02e4228effd9a0,302,1,150.12,4,0.0,0
4,0006fdc98a402fceb4eb0ee528f6a8d4,166,1,29.00,3,0.0,0

In [ ]:
customer_data.shape

(43602, 7)

In [ ]:
customer_data.describe()

,Recency,Frequency,Total_Spent,Average_Review_Score,Avg_Late_Delivery_Days,Repeat_Purchase
count,43602.000000,43602.000000,43602.000000,43602.000000,42064.000000,43602.000000
mean,136.874937,1.031444,165.768599,4.066511,0.673474,0.012866
std,95.595963,0.197801,236.270558,1.345953,5.209940,0.112699
min,0.000000,1.000000,10.070000,1.000000,0.000000,0.000000
25%,47.000000,1.000000,63.000000,4.000000,0.000000,0.000000
50%,123.000000,1.000000,106.190000,5.000000,0.000000,0.000000
75%,213.000000,1.000000,181.550000,5.000000,0.000000,0.000000
max,360.000000,10.000000,13664.080000,5.000000,181.000000,1.000000

In [ ]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43602 entries, 0 to 43601
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_unique_id      43602 non-null  object
 1   Recency                 43602 non-null  int64
 2   Frequency               43602 non-null  int64
 3   Total_Spent             43602 non-null  float64
 4   Average_Review_Score    43602 non-null  int64
 5   Avg_Late_Delivery_Days  42064 non-null  float64
 6   Repeat_Purchase         43602 non-null  int64
dtypes: float64(2), int64(4), object(1)
memory usage: 2.3+ MB

In [ ]:
customer_data['Repeat_Purchase'].value_counts()

Repeat_Purchase
0    43041
1      561
Name: count, dtype: int64

In [ ]:
x = customer_data.drop(columns=['Repeat_Purchase','customer_unique_id'] , axis=1)
y = customer_data['Repeat_Purchase']

In [ ]:
test = testing_data.drop(columns='customer_unique_id' , axis=1)

In [ ]:
x.isna().sum()

Recency                   0
Frequency                 0
Total_Spent               0
Average_Review_Score      0
Avg_Late_Delivery_Days    0
dtype: int64

In [ ]:
x["Avg_Late_Delivery_Days"] = x["Avg_Late_Delivery_Days"].fillna(0)

In [ ]:
testing_data["Avg_Late_Delivery_Days"] = testing_data["Avg_Late_Delivery_Days"].fillna(0)

In [ ]:
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)
model.fit(x, y)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [ ]:
x_training_prediction = model.predict(x)
training_data_accuracy = accuracy_score(x_training_prediction, y)
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.5790560066052016

In [ ]:
y_pred = model.predict(test)
y_prob = model.predict_proba(test)[:, 1]

In [ ]:
testing_data["Predicted_Repeated_Purchase"] = y_pred
testing_data["Repeated_Purchase_Probability"] = y_prob

In [ ]:
testing_data.head()

,customer_unique_id,Recency,Frequency,Total_Spent,Average_Review_Score,Avg_Late_Delivery_Days,Predicted_Churn,Churn_Probability,Predicted_Repeated_Purchase,Repeated_Purchase_Probability
0,0000366f3b9a7992bf8c76cfdf3221e2,52,1,141.90,5,0.0,1,0.529438,1,0.529438
1,0000b849f77a49e4a4ce2b2a4ca5be3f,55,1,27.19,4,0.0,1,0.513201,1,0.513201
2,0004bd2a26a76fe21f786e4fbd80607f,87,1,166.98,4,0.0,0,0.487497,0,0.487497
3,00050ab1314c0e55a6ca13cf7181fecf,67,1,35.38,4,0.0,1,0.509115,1,0.509115
4,00053a61a98854899e70ed204dd4bafe,123,1,419.18,1,0.0,0,0.360719,0,0.360719

In [ ]:
testing_data.to_csv(
    "Amazon_Repeated_Purchase_Predictions.csv",
    index=False
)

In [ ]:
from google.colab import files

files.download("Amazon_Repeated_Purchase_Predictions.csv")

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
model.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [ ]:
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.54      0.70      8609
           1       0.02      0.60      0.03       112

    accuracy                           0.54      8721
   macro avg       0.50      0.57      0.37      8721
weighted avg       0.98      0.54      0.69      8721

[[4670 3939]
 [  45   67]]